version: '2'

services:


  db:
    image: 'mariadb:latest'
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=upanel
      - MARIADB_USER=root
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/src/main/java/pdes/c1/universitypanel/utils/init.sql

  localhost:
    image: 'universitypanel:latest'
    build:
      context: .
    container_name: localhost
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/upanel
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080

  web:
    image: 'universitypanel-web:latest'
    build:
      context: ./src/main/webapp
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 8083:80
    depends_on:
      - localhost