name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: root
          MYSQL_DATABASE: upanel
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build backend
        run: mvn clean install

      - name: Run backend tests
        run: |
          mvn test

      - name: Run backend
        run: |
          mvn spring-boot:run &

      - name: Wait for backend server to start
        run: sleep 10

      - name: Build and test frontend
        run: |
          npm install -g @angular/cli@15.1.6
          cd src/main/webapp
          npm install
          npm run build
          ng serve --open &

      - name: Wait for frontend server to start
        run: sleep 10

      - name: Run Cypress tests
        run: |
          cd src/main/webapp  # Navegar al directorio donde se encuentra el archivo package.json
          npm install         # Instalar las dependencias
          npm run cypress:install
          npm run cypress:run