name: Actions
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: root
          MYSQL_DATABASE: upanel
        ports:
          - 3306:3306
        volumes:
          - universitypanel_init_sql:/src/main/java/pdes/c1/universitypanel/utils/init.sql

    volumes:
      universitypanel_init_sql:

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and test backend
        run: mvn clean install -DskipTests

      - name: Build and test frontend
        run: |
          npm install -g @angular/cli@15.1.6
          cd src/main/webapp
          npm install
          npm run build