name: SonarCloud Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Analyze Maven Project
        run: |
          mvn clean install -DskipTests=true
          mvn sonar:sonar -Dsonar.projectKey=JeremiasFuentes_pdes-unq-grupo3-universitypanel -Dsonar.organization=jeremiasfuentes -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN

      - name: Build and Analyze Angular Project
        uses: actions/setup-node@v2
        with:
          node-version: '14.20'
      - name: Install Dependencies
        run: |
          cd ./src/main/webapp
          npm install
      - name: Build Angular Project
        run: |
          cd ./src/main/webapp
          npm run build
      - name: SonarCloud Scan for Angular
        run: |
          cd ./src/main/webapp
          sonar-scanner -Dsonar.projectKey=JeremiasFuentes_pdes-unq-grupo3-universitypanel -Dsonar.organization=jeremiasfuentes -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
